# Generated by Django 5.0.2 on 2024-02-25 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='sobrenome',
        ),
    ]
