# Generated by Django 5.0.2 on 2024-02-25 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_usuarios', '0002_remove_usuarios_sobrenome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
